language: sh
dist: xenial
python:
  - 3.7

os: windows


before_install:
  - choco install python3
  - export PATH="/c/Python38:/c/Python36/Scripts:$PATH"
  - python -m pip install --upgrade pip wheel
 
install:
  - py -m pip install pipenv
  - python -m pipenv install --system --deploy --ignore-pipfile

env:
  region: us-east-1

stages:
  - test
  - name: answers
    if: branch = master

jobs:
  include:
    - stage: test      
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      before_script: # code coverage tool
         - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
         - chmod +x ./cc-test-reporter
         - ./cc-test-reporter before-build
      script: 
         - pytest --cov-report xml --cov-report term
         - pytest --cov-report xml:coverage.xml --cov-report term
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: answers
      script:
        - make data
        - python3 -m approject