# Generated by Django 3.0.5 on 2020-04-30 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='FactReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('useful', models.CharField(max_length=200)),
                ('funny', models.CharField(max_length=200)),
                ('cool', models.CharField(max_length=200)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_reviews', to='yelp_reviews.DimDate')),
            ],
        ),
    ]
