# Generated by Django 3.0.5 on 2020-04-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factreview',
            name='cool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factreview',
            name='funny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factreview',
            name='useful',
            field=models.IntegerField(default=0),
        ),
    ]
